package com.example.mamikos.model.apiresponse.book.bookdetail

data class BookDetailResult(
    var BookChapter_by_book_id: List<BookDetailChapter> = listOf(),
    var Related_by_book: List<BookDetailRelated> = listOf(),
    var User_review: String = "",
    var Writer_by_writer_id: BookDetailWriter = BookDetailWriter(),
    var average_rate: Int = 0,
    var book_url: String = "",
    var category: Any = Any(),
    var challenge_id: Any = Any(),
    var chapter_count: Int = 0,
    var cover_url: String = "",
    var created_at: String = "",
    var daily: String = "",
    var decimal_rate: Double = 0.0,
    var desc: String = "",
    var download: Any = Any(),
    var full_price: Int = 0,
    var full_purchase: Boolean = false,
    var full_purchased: Boolean = false,
    var genres: List<BookDetailGenre> = listOf(),
    var happyhour: Boolean = false,
    var id: Int = 0,
    var isNew: Boolean = false,
    var is_contract_actived: Boolean = false,
    var is_update: Boolean = false,
    var nominasi: Any = Any(),
    var reviews: List<BookDetailReview> = listOf(),
    var schedule_daily: Int = 0,
    var schedule_task: String = "",
    var status: String = "",
    var synopsis: String = "",
    var time_to_vote: Boolean = false,
    var title: String = "",
    var updated_at: String = "",
    var url_landing: String = "",
    var view_count: Int = 0,
    var vote_count: String = "",
    var voted: Boolean = false,
    var writer_id: Int = 0
)